### ISSUE TITLE
Better documentation 

### ISSUE THREAD

**Issue by andreyevyk** [andyduke/styled_text_package#23]
Many things what i want to use in the project, like a break line, don't are in documentation.

**Comment by andyduke** [comment]
> Many things what i want to use in the project, like a break line, don't are in documentation.

What exactly is missing from the documentation?

**Comment by Zabadam** [comment]
Here are the [escape characters you may use.](https://pub.dev/documentation/styled_text/latest/styled_text/StyledText/text.html) 

New lines may be produced simply by '\n' within the `text` param, considering the [newLinesAsBreaks property](https://pub.dev/documentation/styled_text/latest/styled_text/StyledText/newLineAsBreaks.html).

Unverified, because I haven't tried, but a self-terminating break `<br/>` oughta do the trick as well.

**Comment by apalala-dev** [comment]
This package is great but I believe these things (how to insert new lines, escaping charaters) should be in the Readme file. In french for instance, the apostrophe is pretty common and is not printed if nothing is done. A simple `.replaceAll("\'", "&apos;")` fixes it.

**Comment by andyduke** [comment]
> 
> 
> This package is great but I believe these things (how to insert new lines, escaping charaters) should be in the Readme file. In french for instance, the apostrophe is pretty common and is not printed if nothing is done. A simple `.replaceAll("\'", "&apos;")` fixes it.

I have updated the [Readme](https://pub.dev/packages/styled_text/versions/2.0.0-nullsafety.0) in version 2.0.0 with null-safety.
