### ISSUE TITLE
An example of how handle html tags?

### ISSUE THREAD

**Issue by ademar111190** [andyduke/styled_text_package#57]
It would be nice to have a sample on how to handle some HTML tags such as `<p> <ul>  <li> <ol> <blockquote> <h1,2,3,…> etc…` maybe a default for each one in the library?

**Comment by andyduke** [comment]
@ademar111190 `StyledText` should not be considered as an HTML render, it has a different purpose - the output of formatted text, where XML (not HTML) is used as a markup language, so there are no predefined tags. You need to define the visual representation of the tags yourself. In addition, complex HTML tags like `<table>` are not supported, because this would significantly complicate the widget.
